### ISSUE TITLE
Remove all unused files

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-ydaniju/algernon#29]
Remove all unused files in the application. For instance `todo_controller` in the `spec/unit/helpers` directory was created but not used.

**Comment by andela-ydaniju** [comment]
All files in that directory are in use. 3 under ```dependencies_spec.rb``` and 1 - ```todos_controller.rb``` in ```finder_spec.rb```. I'd check around if there is an unused one though.

**Comment by andela-ydaniju** [comment]
:+1:
